on:
  push:
    branches-ignore:
      - 'main'

jobs:
  run_changed_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip3 install -r tests/requirements.txt

    - name: Run changed tests
      working-directory: tests/
      run: ./run_changed_tests.sh
