name: Test

on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-total: [2]
        node-index: [0, 1]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      working-directory: tests/
      run: pip install -r requirements.txt

    - name: Run tests
      working-directory: tests/
      run: vedro run --slicer-total=${{ matrix.node-total }} --slicer-index=${{ matrix.node-index }}
